using Quality_Control.Forms.Modification.Model;
using System.Collections.Generic;

namespace Quality_Control.Commons
{
    public class QualityFields
    {
        public List<ModificationModel> Fields { get; } = new List<ModificationModel> 
        {
            new ModificationModel(0, "Data", "measure_date"),
            new ModificationModel(1, "Temperatura", "temp"),
            new ModificationModel(2, "Gęstość", "density"),
            new ModificationModel(3, "pH", "pH"),
            new ModificationModel(4, "Lepkość 1 rpm", "vis_1"),
            new ModificationModel(5, "Lepkość 2 rpm", "vis_2"),
            new ModificationModel(6, "Lepkość 5 rpm", "vis_5"),
            new ModificationModel(7, "Lepkość 10 rpm", "vis_10"),
            new ModificationModel(8, "Lepkość 15 rpm", "vis_15"),
            new ModificationModel(9, "Lepkość 20 rpm", "vis_20"),
            new ModificationModel(10, "Lepkość 25 rpm", "vis_25"),
            new ModificationModel(11, "Lepkość 30 rpm", "vis_30"),
            new ModificationModel(12, "Lepkość 35 rpm", "vis_35"),
            new ModificationModel(13, "Lepkość 40 rpm", "vis_40"),
            new ModificationModel(14, "Lepkość 45 rpm", "vis_45"),
            new ModificationModel(15, "Lepkość 50 rpm", "vis_50"),
            new ModificationModel(16, "Lepkość 55 rpm", "vis_55"),
            new ModificationModel(17, "Lepkość 60 rpm", "vis_60"),
            new ModificationModel(18, "Lepkość 65 rpm", "vis_65"),
            new ModificationModel(19, "Lepkość 70 rpm", "vis_70"),
            new ModificationModel(20, "Lepkość 75 rpm", "vis_75"),
            new ModificationModel(21, "Lepkość 80 rpm", "vis_80"),
            new ModificationModel(22, "Lepkość 85 rpm", "vis_85"),
            new ModificationModel(23, "Lepkość 90 rpm", "vis_90"),
            new ModificationModel(24, "Lepkość 95 rpm", "vis_95"),
            new ModificationModel(25, "Lepkość 100 rpm", "vis_100"),
            new ModificationModel(26, "Dysk numer", "disc"),
            new ModificationModel(27, "Lepkość uwagi", "visc_remarks"),
            new ModificationModel(28, "Krycie 75um", "contrast_75"),
            new ModificationModel(29, "Krycie 100um", "contrast_100"),
            new ModificationModel(30, "Krycie 125um", "contrast_125"),
            new ModificationModel(31, "Krycie 150um", "contrast_150"),
            new ModificationModel(32, "Krycie 200um", "contrast_200"),
            new ModificationModel(33, "Krycie 240um", "contrast_240"),
            new ModificationModel(34, "Krycie 250um", "contrast_250"),
            new ModificationModel(35, "Krycie 300um", "contrast_300"),
            new ModificationModel(36, "Krycie śrubowy 100um", "contrast_wire_100"),
            new ModificationModel(37, "Krycie śrubowy 125um", "contrast_wire_125"),
            new ModificationModel(38, "Krycie śrubowy 150um", "contrast_wire_150"),
            new ModificationModel(39, "Krycie śrubowy 200um", "contrast_wire_200"),
            new ModificationModel(40, "Krycie śrubowy 250um", "contrast_wire_250"),
            new ModificationModel(41, "Krycie klasa", "contrast_class"),
            new ModificationModel(42, "Krycie uwagi", "contrast_remarks"),
            new ModificationModel(43, "L na mokro", "L_m"),
            new ModificationModel(44, "a na mokro", "a_m"),
            new ModificationModel(45, "b na mokro", "b_m"),
            new ModificationModel(46, "WI na mokro", "WI_m"),
            new ModificationModel(47, "YI na mokro", "YI_m"),
            new ModificationModel(48, "L na sucho", "L_s"),
            new ModificationModel(49, "a na sucho", "a_s"),
            new ModificationModel(50, "b na sucho", "b_s"),
            new ModificationModel(51, "WI na sucho", "WI_s"),
            new ModificationModel(52, "YI na sucho", "YI_s"),
            new ModificationModel(53, "DE", "DE"),
            new ModificationModel(54, "Spektro uwagi", "spectro_remarks"),
            new ModificationModel(55, "Połysk 20", "gloss_20"),
            new ModificationModel(56, "Połysk 60", "gloss_60"),
            new ModificationModel(57, "Połysk 85", "gloss_85"),
            new ModificationModel(58, "Połysk uwagi", "spectro_remarks"),
            new ModificationModel(59, "Czas schnięcia I-szy stopień", "drying_I"),
            new ModificationModel(60, "Czas schnięcia II-gi stopień", "drying_II"),
            new ModificationModel(61, "Czas schnięcia III-ci stopień", "drying_III"),
            new ModificationModel(62, "Czas schnięcia IV-ty stopień", "drying_IV"),
            new ModificationModel(63, "Czas schnięcia V-ty stopień", "drying_V"),
            new ModificationModel(64, "Czas schnięcia VI-ty stopień", "drying_VI"),
            new ModificationModel(65, "Czas schnięcia VII-my stopień", "drying_VII"),
            new ModificationModel(66, "Czas schnięcia uwagi", "drying_remarks"),
            new ModificationModel(67, "Szorowanie szczotka", "scrubing_brush"),
            new ModificationModel(68, "Szorowanie gąbka", "scrubing_sponge"),
            new ModificationModel(69, "Szorowanie uwagi", "scrubing_remarks"),
            new ModificationModel(70, "Rozlewność", "flow"),
            new ModificationModel(71, "Spływność", "runoff"),
            new ModificationModel(72, "Przyczepność", "adhesion"),
            new ModificationModel(73, "Części stałe", "f_solids"),
            new ModificationModel(74, "Popiół w 450oC", "f_450"),
            new ModificationModel(75, "Popiół w 900oC", "f_900"),
            new ModificationModel(76, "Części organiczne", "f_organic"),
            new ModificationModel(77, "Zawartość kredy", "f_lime"),
            new ModificationModel(78, "Zawartość talku", "f_talcum"),
            new ModificationModel(79, "Zawartość dwutlenku tytanu", "f_titanium"),
            new ModificationModel(80, "VOC ilość g/l", "VOC"),
            new ModificationModel(81, "Spalanie uwagi", "f_remarks"),
            new ModificationModel(82, "Uwagi ogólne do całości", "comments")
        };
    }
}
